name: Auto-Build
on:
  push

env:
    FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
    TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 9

      - name: Test
        run: dotnet test -c release
