name: Release
on:
  workflow_dispatch:
    branches: [ master ]

env:
    FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
    TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 8

      - name: Build
        run: |
            sed -i "s/\(<Version>\([0-9]\+\.\)\{3\}\)\([0-9]\+\)/\1${{github.run_number}}/" "DustyPig.Firebase.Auth/DustyPig.Firebase.Auth.csproj"
            dotnet pack -c release -o nuget
            dotnet nuget push "nuget/*.nupkg" --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
        